### PR TITLE
Coriska reader: Use buffered IO for input stream

### PR DESCRIPTION
**Pull request by tomkooij**
I know this is just procrastinating, but I profiled conversion of DAT000000 to HDF5:
https://gist.github.com/tomkooij/74d2ef3276114bfb7ae159f9bfc7c602

A lot of time is spent in ```file.read``` and ```file.seek```.
This PR seems to solve that (somewhat) by using the python built-in BufferedIO. (I didn't know it existed).

I've only tested a 250 Mb file. It's about 30% faster. (2m40 -> 1m40). ```h5diff``` thinks the output files are identical.

### CODE REVIEW

**Comment by tomkooij** [comment]
Unfortunately, on a 1Gb file there hardly seems to be any difference.. Too bad!

**Comment by 153957** [comment]
Haha, I was just thinking about something like this. For instance instead of reading particle per particle read subblocks of particles at a time. i.e. in `_unpack_particle` unpack a block of particles instead of a single particle.

**Comment by tomkooij** [comment]
Totally useless, but still fun!

Using "built-in" bufferedIO would have been a quick fix, but I guess the processing of particles per word is still a bigger bottleneck than file IO. Unpacking a large block of particles should really help reducing the number of function calls.

```blocks.particle_data``` needs to be cythonized as well ;)

Anyway, I'll try not to spend too much time on this...

**Comment by 153957** [comment]
I'll try the unpack multiple particle thing. Than work on more important things :)

**Comment by 153957** [comment]
During the `source.check()` step my Mac caches the entire file in RAM (if it fits) and then works from that. Not certain if the file is then in a system IO buffer or in Python, but seem CPU limited then.

**Pull request closed without merging**
