### PR TITLE
Use numba jit on particle_data()

### PR DESCRIPTION
**Pull request by tomkooij**
This adds another 25% speed up on top of: 41cfdce97b514dadfbbd150515a2ae77743b96ca

DAT000000 -> hdf5 is 50% faster on a 1Gb file, as compared to this morning. It does depend on numba, but I do think it is worth it. 

The conditional import does not seems to work...

### CODE REVIEW

**Comment by 153957** [comment]
Ah ok, I was worried about an additional requirement, the conditional import works around that.

**Comment by tomkooij** [comment]
I actually tested the conditional import this time ;)

This only needs ```conda install numba``` for an almost free speed-up.

**Comment by 153957** [comment]
Haha, I was just about to ask, can you write a test that tests both cases?

**Comment by tomkooij** [comment]
Will write test... Patching/mocking a module. That should be interesting.

**Comment by 153957** [comment]
Just assume it will be available (Add install to `travis.yml`) then patch/mock the decorator in a test.

**Comment by 153957** [comment]
I installed numba and the jit branch in the corsika env.
I started a job for the new largest shower `397124573_252130580`,
but the queue is a bit full at the moment so it will (hopefully) start later today.

**Comment by tomkooij** [comment]
This unittest works with and without numba installed. Without numba it just tests ```particle_data()```. When numba is available it tests with and without the ```@jit``` decorator.

**Comment by tomkooij** [comment]
No clue why Travis fails. A local ```make test``` passes and It passed before adding the tests.

I'll try to ```reload(blocks)``` at tearDown(), to fix the @patched decorator.

**Comment by 153957** [comment]
Hmm, this is annoying.
I tried some ways I could think of that might fix this, but none helped.

**Comment by tomkooij** [comment]
I bisected it down to just the ```reload(blocks)```. This is some annoying import problem. However reload is necessary after patching a decorator, because the decorator is applied at import.

I refactored the test to prevent patching the decorator. 

Locally this works:
```
>>> run test_blocks.py
>>> run test_corsika.py
```

**Comment by 153957** [comment]
The current test error is due to station 3701 (Leiden) becoming active. It already existed, but had now uploaded data and a config. Update the test data and it should work.

The problem is that the decorator is applied on import, so it can not simply be patched without reloading. I tried to 'unpatch' it (reassign the original function to `numba.jit`) and then reload blocks in the `tearDown`, but that did not seem to work.. I also couldn't find a good tip on SO..

**Comment by tomkooij** [comment]
I ran ```update_local_data``` and ```esd_load_data``` but I cannot push master, so I merged it into this.

**Pull request merged**
