### PR TITLE
Deprecation fixes

### PR DESCRIPTION
**Pull request by 153957**
These issues showed up as warnings during tests.

> PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.

> DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.

### CODE REVIEW

**Comment by 153957** [comment]
Nice and short Travis logs, from 2900 lines to 1000 lines.

**Comment by 153957** [comment]
The unittests still print a progressbar, probably for some analysis method called during a test where it was not properly disabled:

https://travis-ci.org/HiSPARC/sapphire/jobs/416257439#L863

We should find out where it comes from to silence it during tests.

**Comment by davidfokkema** [comment]
Sorry, I didn't find time earlier. Looks good to me! (where do *you* find all the time you put into this?)

**Comment by 153957** [comment]
Sleep is overrated 😉

**Pull request merged**
