### PR TITLE
Use station offsets in direction reconstruction

### PR DESCRIPTION
**Pull request by tomkooij**
This implements support for station offsets in direction reconstructions.

This is a "initial guess" at implementing station offsets in direction reconstructions.

Not yet ready to be merged.

TODO:
- [x] Check results
- [x] Figure out how to handle reference stations
- [x] Try to minimise NaNs (try different reference, try "via")
- [x] Minimize errors (try via other stations)
- [x] Implement in subclasses
    - [x] reconstructions.py
    - [x] direction_reconstructions.py
- [x] Ensure it does not break reconstructions from simulations (i.e. fake clusters)
    - [x] Use offsets generated during simulation 
- [x] Handle NaNs and missing/unavailable data
- [x] Tests
- [ ] ~~Add detector/station offsets to local data (update tests)~~ Todo later, after recalculating offsets with correct altitude corrections

### CODE REVIEW

**Comment by tomkooij** [comment]
It seems to work (although the number of reconstructed events is low, will have to look into that.)
Left is station offsets as in 'master', right is this branch.

501,504,505:
azimuth_501_504_505

501,502,505
azimuth_501_502_505

Source: https://github.com/tomkooij/lio-project/blob/master/offsets/try_station_offsets.py

**Comment by tomkooij** [comment]
501, 502, 508 is actually quite nice:
azimuth_501_502_508

**Comment by davidfokkema** [comment]
Looking good!

**Comment by tomkooij** [comment]
New idea to handle reference stations:
Goal: Minimize NaNs in offsets. (Better would be to optimize quality of offsets, but we cannot measure that (yet?) )

foreach station in coincidence:
- Use this station as reference
- foreach station in coincidence: Calc offsets, count NaNs
- No NaNs? -> use this
- NaNs? Store if number of NaNs is less than a previous attempt
Use offsets with least number of NaNs
 
(offsets is a dict of values is not implemented, so the tests fail)

**Comment by 153957** [comment]
I called `determine_best_offsets` multiple times shuffling the order of the station numbers which it first attempts as reference. The resulting offset dictionary has been shifted to make detector 2 of 501 the reference. Only the offet for detector 2 of each station is shown. Observe the changes. Especially the first and last sets are different from the middle two. The offset of 510 shifts quite a lot for the last set. In most cases the differences are within ~5 ns. Which seems acceptable.

```json
501   0.0   0.0   0.0   0.0 
502   8.1  12.8  12.5   7.4 
503  -5.4  -1.5  -6.9  -7.9 
504  18.8  22.7  22.4  17.3 
505  13.0  11.8  11.5   6.4 
506   5.5   9.4   9.9   4.8 
507 -24.3 -19.6 -19.9 -25.0 
508   6.1   6.7   6.4   1.3 
509  -1.6   3.1   2.8  -2.3 
510   8.3   7.9   8.6   0.0 
```

**Comment by 153957** [comment]
Note that normally a list of possible reference stations is created from the stations in the coincidence and those available in offsets. The set does not have a defined order, so for the previous post I added
`shuffle(station_numbers)` to randomize which station would (first) be used as reference.

**Comment by tomkooij** [comment]
Can you do this for a group of nearby stations (ie max 300 m?): SPA without [509, 504] (and perhaps without 507). The standard error should be reasonable for such station pairs, but may be quite big when 509 and 504 are involved. 

I wonder if systematic (timing) errors can be deduced from such a table.

**Comment by 153957** [comment]
Here the offsets between Science Park stations, not using 504/507/509, neither as reference nor via station (i.e. they not in `offsets`, so can not be used as intermediate station). The station number above each column is the reference_station for the offsets in that column.

sn  |   501 |   502 |   503 |   505 |   506 |   508 |   510 |   511
----|-------|-------|-------|-------|-------|-------|-------|-------
501 |   0.0 |   0.0 |   0.0 |   0.0 |   0.0 |   0.0 |   0.0 |   0.0
502 |  12.5 |  12.5 |  11.5 |  14.7 |   8.1 |  12.5 |  12.5 |  16.5
503 |  -7.9 |  -6.9 |  -7.9 |  -6.1 |  -5.4 |  -7.6 |  -5.6 |  -0.6
505 |   9.5 |   7.3 |   7.7 |   9.5 |  10.2 |  11.6 |  12.6 |  11.3
506 |   5.5 |   9.9 |   3.0 |   4.8 |   5.5 |   5.8 |   5.8 |   8.6
508 |   6.4 |   6.4 |   6.1 |   4.3 |   6.1 |   6.4 |   6.4 |   6.1
510 |   8.6 |   8.6 |   6.3 |   5.5 |   8.3 |   8.6 |   8.6 |   8.3
511 | -44.8 | -48.8 | -52.1 | -46.6 | -47.9 | -44.5 | -44.5 | -44.8

**Comment by tomkooij** [comment]
Nice!

A quick hack to find the best reference seems to be "Find all reference stations without NaNs, choose the reference that is nearest to the center of mass of the cluster".

Or even better: "choose station closest to center of mass as reference, try to fix NaNs by "hopping" via other stations".

**Comment by 153957** [comment]
Indeed, but not only 'try to fix nans', also 'try to minimize offsets error by hopping'.
And should 'use closest to center of mass' only consider the stations in the coincidence?
Or at least determine the center of mass from stations in the coincidence, then find out whatever station is closest to that point, even a station not in the coincidence..

**Comment by tomkooij** [comment]
Ok, I brushed up on algorithms (code below). Finding all shortest path between pairs on a graph is `Floyd-Warshall` The algorithm is in `scipy`, but we will need to implement our own version that adds standard errors (SE) by sqrt(SE1^2+SE2^2). 

Disregarding that, implementation and finding the best reference is easy:
Just put the distances (SE) between pairs in a matrix, find the shortest path, store it in a matrix. 
Find the row with the smallest sum of all items in the row.

Now just implement `Floyd-Warshall` with the correct way of adding SE.

```python
"""
Find best reference station for station timing offsets
Use Floyd-Warshall to find minimum distance (= Standard Error)
 between all stations pairs. NaN => Infinity
The best reference is the station with the lowest sum of distances

 to the other stations.
"""
import numpy as np
from scipy.sparse.csgraph import floyd_warshall

from sapphire import Station

#SPA = range(501, 511)
SPA = [501, 502, 503, 505, 506, 508, 510, 511]

s_dict = {}
for sn in SPA:
    s_dict[sn] = Station(sn, force_stale=True)


def get_offset_SE(sn, ref_sn):
    """return SE on the timing offset for station pair."""
    try:
        off = s_dict[sn].station_timing_offset(ref_sn)
    except:  # sn = ref_sn --> 'distance' = 0
        off = (0,0)
    #print "%d : %d SE = %3.2f" % (sn, ref_sn, off[1]) 
    return off[1]


s_matrix = np.array([get_offset_SE(sn, ref_sn) for sn in SPA for ref_sn in SPA])
s_matrix = s_matrix.reshape(len(SPA), len(SPA))

shortest_paths = floyd_warshall(s_matrix)
total_SE = map(sum, shortest_paths)

for idx, sn in enumerate(SPA):
    print "%d : best sum SE %3.2f" % (sn, total_SE[idx])

print "Best is %3.2f" % min(total_SE)
```

Output:

```
In [7]: run SPA.py
501 : best sum SE 5.94
502 : best sum SE 7.38
503 : best sum SE 9.65
505 : best sum SE 12.37
506 : best sum SE 11.07
508 : best sum SE 5.92
510 : best sum SE 5.88
511 : best sum SE 9.09
Best is 5.88
```

Even with the wrong way off adding SE, this is not bad.

**Comment by 153957** [comment]
Why not simply put the squared SE in the matrix? For comparison the sqrt does not make a difference, and at least the paths are summed correctly.

Unfortunately the floyd_warshall documentation is not extremely clear, it is without examples, can the 'predecessors' be used to reconstruct the shortest path and get the actual offsets?

**Comment by tomkooij** [comment]
Squares, yes!

`return_predecessors=True` returns a matrix from which the actual paths may? be reconstructed. I have not tried it yet.

The implementation is in Cython, so I would prefer using `scipy`: https://github.com/scipy/scipy/blob/e2dd37d745bf7e2d5280492c3e3a2cb025a0a345/scipy/sparse/csgraph/_shortest_path.pyx#L181

**Comment by 153957** [comment]
I updated the example with `** 2` and `np.sqrt`.

**Comment by 153957** [comment]
I think I understand the predecessor matrix, Im writing some example code that should reconstruct the path.

**Comment by 153957** [comment]
This can probably be cleaned up a bit, but this should work for now:

```python
def reconstruct_path(predecessors, start, end, nodes):
    path = [end]
    i = nodes.index(start)
    j = nodes.index(end)
    k = pred[i, j]
    path.append(nodes[k])
    while k != i:
        k = pred[i, k]
        path.append(nodes[k])
    path.reverse()
    return path

reconstruct_path(pred, 501, 505, SPA)
# [501, 510, 508, 511, 505]
reconstruct_path(pred, 506, 511, SPA)
# [506, 508, 511]
```

**Comment by 153957** [comment]
If I understand correctly you sum the shortest_paths to get the best reference station? (the one with the overall shortest paths to other stations). I updated the code in you example to use the more descriptive `shortest_path` from scipy and to sum the array using `.sum()`, and updated the result.

**Comment by tomkooij** [comment]
Yes, the reference station with the overall smallest sum of (squared) SE. The example seems correct to me.

**Comment by 153957** [comment]
Thanks for the idea/hint/example! this works quite well, even for the entire network with a small tweak. We still need to handle nans and stations far apart, which currently get (0, 100).

**Comment by tomkooij** [comment]
Why not set (nan, nan) offsets to (0, 100) for direction reconstruction. (But leave as NaN/None on the server).

The shortest path algorithm will then choose a path that excludes this offset, if possible. If not possible the "total" SE for the entire coincidence will be large, say >100 ns.  We can then (optionally) exclude such a conicidence from direction reconstruction. Perhaps set the maximum SE as a kwarg.

**Comment by 153957** [comment]
I think I though of a reason why this was not a good idea, but do not recall the exact reasoning. One of the reasons is that the nans are also for the days on which the offsets change, making them unpredictable, but again that is what the (0, 100) is for..

It may also have to do with pathing, if for example the reference ends up to be 501 for some extraordinarily large coincidence, which also includes stations 2001 and 2002, which have no offset to 501. The offsets for those will then both be 0, because the shortest path from them to the reference is direct. So their offsets to each other will not be taken into account.. However, this problem is also not fixed by setting all (nan, nan) to (0, 100).. It is a problem that should not occur that often anyways.. Moreover, this is a slightly unrelated problem..

**Comment by 153957** [comment]
Direction reconstructions take about twice as long with these modifications. This can be helped by adding `@memoize` to `determine_best_offsets` and flooring the coincidence timestamp `ts0` to the previous midnight (`floor_in_base(ts0, 86400)`). Since offsets are determined daily, coincidences on the same day can reuse the same offsets, given the same stations are in the coincidence (or a list of station numbers is provided).

**Comment by 153957** [comment]
For a Science Park dataset I have with ~1 month of data direction reconstruction took ~10 minutes without memoize, with it the speed is back to less than 5 minutes, so a nice gain.

**Pull request merged**
