### PR TITLE
Add distance_between_stations() method to BaseCluster

### PR DESCRIPTION
**Pull request by tomkooij**
I keep importing a method like this from some script somewhere. Time to add it to sapphire.

```
>>> from sapphire import ScienceParkCluster
>>> s = ScienceParkCluster()
>>> s.calc_distance_between_stations(501, 502)
87.588467506050165
```

To do:
- [x] change methods to  ```calc_``` to fit into the ```BaseCluster``` class.
- [x] Add tests

### CODE REVIEW

**Comment by tomkooij** [comment]
I'm happy with this. @153957 Please merge if you are happy.

**Comment by 153957** [comment]
Looks good. I updated the docstring to clarify the definition of the horizontal distance.

**Comment by davidfokkema** [comment]
There was this:
```
>>> from sapphire import ScienceParkCluster
>>> s = ScienceParkCluster()
>>> s.calc_rphiz_for_stations(0, 1)
(87.58837006940124, -2.3851505721950526, -0.13064702072029588)
```
Granted, the new method is easier to use.

**Comment by 153957** [comment]
indeed, the new one can do the combinations of r and z directly and allows using of station numbers instead of ids.

**Comment by davidfokkema** [comment]
And it has a *slightly* better name! 😜

**Pull request merged**
