### PR TITLE
Use standard error of the mean for error of station timing offsets

### PR DESCRIPTION
**Pull request by 153957**
`error = σ / √n` - https://en.wikipedia.org/wiki/Standard_error

Unlike the rchi2 used previously this correctly increases the error if the distribution becomes wider and the number of counts is reduced.

### CODE REVIEW

**Comment by 153957** [comment]
Previous reduced chi squared errors:
rchi2

New standard errors:
error

The new errors are more useful, they more accurately represent the errors
These errors can also be propagated when determining offsets via other stations.

**Comment by davidfokkema** [comment]
There are a lot of changes. For example, the 501 vs 503 are much smaller, but the errors for 501 vs 504 are much bigger. Are those differences understood? I love the plot, by the way!

**Comment by 153957** [comment]
The error increases with the width of the distribution, which increases with the distance between stations. The coincidence rate decreases as distance increases, which increases the error. An attempt it made to compensate by increasing the number of days from which data is used, however, this does not reduce the error to similar levels as for stations closer together. Some of the spikes are likely due to periods with fewer events.

501 - 503 are separated by 140 m.
501 - 504 are separated by 270 m.

**Comment by tomkooij** [comment]
+1 for the plot.

I would like to see the data for periods that cause the big spike in standard error. 

I like the standard error as parameter for quality of the timing offsets. However, using the SE implies that the data is indeed gaussian. In our algorithm we do fit a gaussian and return NaN if the fit fails, but I (still, perhaps incorrectly) wonder if the data is a combinations of two (non-overlapping) gaussians with significant different mean values.  

It seems this is a real possibility if there is a real shift in timing offset in the data taking period. I've seen the plot (501/510?) with two separate bumps, so this is probably easy to investigate.

Anyway, even in that case the SE is a much better parameter for the offset error than the Chi2 goodness of fit! Nice work!

**Comment by 153957** [comment]
Here is the plot you refer to, indeed between 510 and 501. Within this period was a GPS location change, which caused the two separate distributions. In this case, because of the large difference in mean and small sigma, the two distributions are entirely separate. Here the fit picked one of the distributions. The resulting error would be underestimated in this case, because the second distribution also counts towards the `n`. It is also clear that the distributions are not perfectly Gaussian, though the distribution is more Gaussian like when the stations are separated by 200-400 m.



Here is an overview of the station offsets. Most jumps in offset occur at the moment the configs (GPS/electronics) are changed. The red lines indicate a change in configs. However, at some points a slope or jump is observed between config changes, this may indicate other causes for changing offsets. This is mostly seen for stations 509 and 505. Note that short perfectly horizontal stretches are likely due to parts which are nan or do not exist because of no data. The nan points are not plotted, but the values before and after it are connected.

station_offsets

**Pull request merged**
