### PR TITLE
append() many, flush() once

### PR DESCRIPTION
**Pull request by tomkooij**
For performance we need to append() many rows but flush() once.
However this breaks event_id = len(table).

Implemented _read_line_and_store_event as contextmanger that has an internal "event_counter" and only flushes at __exit__

ToDo:
- [ ] ~~tests/test_esd.py is incomplete. Add tests for esd.download_data() and esd.download.coincidences() similar to the tests for load_data()~~ in #69 
- [x] compare speed

### CODE REVIEW

**Comment by 153957** [comment]
About tests for `download_data` and `download_coincidences`: Use short periods/easy queries, to prevent putting to much strain on the server and add a decorator like the tests for the API to skip them if the user can not connect to the server.

**Comment by tomkooij** [comment]
esd.quick_download() is actually SLOWER in this branch :( 
It might just be the horrible network performance at my current location.

@153957: I'll implement the tests anyway, in a seperate branch.

**Comment by tomkooij** [comment]
Performance improvement seems consistent with 892456b
Passes the new tests of #69.

esd.py is a bit inconsistent with a classess and functions mixed.
@153957 : Please review and merge (or throw away).

**Comment by tomkooij** [comment]
https://github.com/HiSPARC/sapphire/blob/fix_esd_speed/sapphire/esd.py#L465 probably broken.
This passes the tests in #69 so tests broken (incomplete)

**Pull request merged**
