### PR TITLE
4 dimensional stations

### PR DESCRIPTION
**Pull request by 153957**
PR for #63.

Add time awareness to Cluster objects. Allow setting a 'timestamps' and get station/detector positions relevant for that timestamp.

Todo:
- [x] Setting the timestamp for the cluster
- [x] Read station layout csv API
- [x] Initializing a station with multiple GPS (ENU) locations
- [x] Initializing detectors with multiple ENU locations
- [x] Activating the relevant positions
- [x] Still work when called with just one location..
- [x] Deal with stations without submitted layouts
- [x] Deal with (0, 0, 0) coordinates (*Removed from Source CSV on publicdb*).
- [x] Use 4D stations in reconstructions
- [ ] Speed up position retrieval for stations/detector by internally caching the values.
- [x] Tests
    - [x] Fix old tests
    - [x] Make some 4D tests
    - [x] Check if correct positions are used in reconstructions

### CODE REVIEW

**Comment by 153957** [comment]
It seems to be working, all detector positions for 501 (for each timestamp on the station, i.e. change in GPS coordinates):

screen shot 2015-06-18 at 09 42 18

4 bad locations indicated with blue rectangles:
- far left - temporary GPS in the window sil
- bottom - temporary 'test' GPS, also used for tijdtest
- far right - seems like original GPS lcoation, but new detector positions (probably non-matching timestamps for the transistion)
- overlapping current location - swapped GPS between 501 and 510

The original location in the small purple rectangle contains many slightly offset locations, probably due to all the self-surveys returning slightly different results.

**Comment by davidfokkema** [comment]
Nice!

**Comment by 153957** [comment]
Still one test failing that may require an extra check.
Possibly due to change in corner order (or orientation of the detector).

```
FAIL: test_get_particles_query_string (sapphire.tests.simulations.test_groundparticles.DetectorBoundarySimulationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sapphire/sapphire/tests/simulations/test_groundparticles.py", line 105, in test_get_particles_query_string
 
AssertionError: Expected call:
read_where('(x >= -0.600000) & (x <= 0.600000) & (y >= 8.060254) & (y <= 9.260254) & (b11 < y - 0.000000 * x) & (y - 0.000000 * x < b12) & (b21 < x) & (x < b22) & (particle_id >= 2) & (particle_id <= 6)')
Actual call:
read_where('(x >= -0.600000) & (x <= 0.600000) & (y >= 8.060254) & (y <= 9.260254) & (b11 < x) & (x < b12) & (b21 < y - -0.000000 * x) & (y - -0.000000 * x < b22) & (particle_id >= 2) & (particle_id <= 6)')
```

**Comment by 153957** [comment]
Wohoo, almost done....

**Comment by 153957** [comment]
Im using the `hasattr(..., '__len__')` to detect if the submitted coordinates are lists.
Other options that do not work in this case:
- `type(..) in (list, tuple, ...)` not certain what else to test for, all kinds of numpy arrays.. 
- `isinstance(.., collections.Sequence)` does not recognize numpy arrays. 
- `hasattr(.., '__getitem__')` is also true for non-lists, like numpy.float64()..

**Comment by 153957** [comment]
I've fixed the locations of the 501 detectors.
This required adding 9 more station layouts to the database.
Because the GPS moved back and forth multiple times..

Open circles are the GPS locations, the colored discs are the detector locations:
4D layout 501

**Comment by 153957** [comment]
@davidfokkema Stations 502, 503, and 506 all have a configuration with a GPS locations around the 501 location. For 502 and 506 these locations are at the end of 2009 and start of 2010. Both have operational data from before the first configuration in the database.

I assume that those configurations with positions at Nikhef are simply from testing and that those stations were never actually located at the Nikhef?

The bad gps location for station 503 is from 26 September 2012, this is related to the swapping of the HiSPARC II electronics with HiSPARC III which contained the Nikhef location..

e.g. 506:
4D layout 506

**Comment by davidfokkema** [comment]
Indeed, those stations were never located at Nikhef. We have changed hardware around due to a firmware upgrade. Maybe you can see if the hardware numbers changed during that period. I'm not sure. However, you can safely remove those configurations. Maybe, just to be sure, write down the dates.

**Comment by 153957** [comment]
Remove them from raw data (and publicdb)?
I could move them to a test station..

**Comment by davidfokkema** [comment]
Maybe that's better!

**Comment by 153957** [comment]
I will add the script for the config migration to `HiSPARC/datastore/migrations`.

**Comment by 153957** [comment]
See https://github.com/HiSPARC/datastore/commit/ea9776e49f1841becaf24d7b33f620ed4ffbe12b

I could not find the configurations for 502 and 506 in the raw data... so I removed their database entries.
As cleanup for 503 I simply removed its config node from the raw data (contained only the one bad config) and also from the database. (Note that the Summaries were also updated to reflect the correct number of configurations, i.e. null).

**Comment by 153957** [comment]
Also added the 'old' layout for station 502. All detectors except detector 2 are in the same location, detector 2 used to be in the middle.
Only the shift of 2 detectors (2 and 4) of station 505 (27/8/2014) and the layout of 507 are still missing.

**Comment by davidfokkema** [comment]
👍

**Pull request merged**
