### PR TITLE
Enable progress bar for Coincidence reconstruction

### PR DESCRIPTION
**Pull request by 153957**
Using with table.nrows as length.

### CODE REVIEW

**Comment by tomkooij** [comment]
For some reason (my?) git is broken, so I cannot ```git fetch``` to test on a stoomboot interactive node with a large coinc file. No time to figure out what is wrong with git.

**Comment by 153957** [comment]
`which git`?

You could (as last resort..) use `wget ..; python setup.py ...` or `pip install [github url]`..

**Comment by tomkooij** [comment]
```git fetch``` did not work for some reason. I was complaining about an empty branch ```No changes - did you forget to use 'git add'?``` and refusing to fetch again. The branch seems fine on Github. 
I removed sapphire from /home/tkooij and used ```git clone``` to install it again.

The progressbar seems to work. Using table.nrows can be reliable (only coincidences in the first few rows out of 1e6 rows). But for my analyses having a pbar during reconstructions is helpful and seem to work.

The tests are broken: 
```data = MagicMock()``` 
probably needs:
``` data.root.coincidences.coincidences.nrows = 1```
 
To be continued...

**Comment by 153957** [comment]
Cool, looks good!

Je hebt de laatste commit gedaan zonder mail adres. Niet heel erg want je naam staat er wel bij.
Ik kan het wel nog corrigeren met een force push.. maarja, niet super belangrijk.

**Comment by tomkooij** [comment]
O, I messed up my git config. Nice... I fixed it on my local branch, but won't force push it, don't know if that is possible, but it might break even more...

**Comment by 153957** [comment]
Nope, only David and I are allowed to force push. You could push the other commit (with correct name/email) under a different branch name and make a pull request for that. and then simply delete this branch..

**Comment by 153957** [comment]
Hmm, you have used multiple author name/emails in the past..
```
    38  tomkooij <tomkooij_at_tomkooij.nl>
     7  Tom Kooij <tomkooij_at_tomkooij.nl>
     3  Tom Kooij <tkooij_at_nikhef.nl>
```

for now I will merge this, we may clean the author list later..

**Pull request merged**
