### PR TITLE
Fix Station.gps_location(date=None)

### LINKED ISSUE #137: Station().gps_location() broken
```python
In [4]: Station(501).gps_location()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-810c1eafe321> in <module>()
----> 1 Station(501).gps_location()

/data/hisparc/tom/sapphire/sapphire/api.pyc in gps_location(self, timestamp)
    854         """
    855         if timestamp is None:
--> 856             timestamp = process_time(self.date)
    857         else:
    858             timestamp = process_time(timestamp)

AttributeError: 'Station' object has no attribute 'date'
```

I'll push a fix.

### PR DESCRIPTION
**Pull request by tomkooij**
Fixes #137 

Station has no attribute 'date'.
If date=None: set date to today.
This behaviour is similar to other methods.

### CODE REVIEW

**Comment by 153957** [comment]
I believe `Station.gps_location` now takes over all the functionality currently in `Station.location(self, date=None)`. You can request the location for any specific moment, or get the latest by skipping the dae/timestamp. We should deprecate/remove the location method. And do the same for the `detectors`->`station_layout` methods.

**Comment by 153957** [comment]
And there is indeed no `self.date` but there is a `self.year, self.month, self.day`, created in the init, but possibly just empty strings... I suppose it need some revising now that most data is taken form the TSV data.

**Comment by tomkooij** [comment]
For future reference: (When I have some time to fix this:)

Consistency of date= in class __init__ and/or methods: Remove from __init___
- date= can be removed from Station().__init__()
- Add date= to Station().info[]
- All other methods: Date=none implies "today/now"

**Comment by 153957** [comment]
I removed the 'duplicate' methods and removed the date support from the init. Also removed date support from info. Since it will mostly be used for country/cluster/subcluster/name, for which we do not support changed over time. n_detectors still counts on scintillator data in info.. the accuracy of which is already questionable.

**Comment by 153957** [comment]
Perhaps we should change the other methods which take a timestamp as argument to make the timestamp optional. Incase it is not given just return the latest value (`idx = -1`). This is already done for `gps_locations`, though could be more efficient by just settings the `idx`, instead of getting the current date.. etc..

**Comment by 153957** [comment]
Todo:

- [ ] Add test for when timestamp=None

**Pull request merged**
