### PR TITLE
Curved front

### PR DESCRIPTION
**Pull request by 153957**
For both 2D and 3D clusters, for 3D the altitudes of the detectors
is taken into account, this is still in progress.

- [x] Implement 3D version
- [x] Make shape energy/size/.. dependent
- [x] Pass information from core to direction reconstructions and vice-versa
- [ ] More tests
- [ ] ...

### CODE REVIEW

**Comment by 153957** [comment]
Commit 986eb28 solves most of #61.

**Comment by 153957** [comment]
Simple test using a 1e16 eV proton 0° shower simulated on Science Park to asses the improvement of curved reconstruction.

The plot shows the angle between the reconstructed and input (0°) angle. So in this case simply the reconstructed zenith angle. The solid line is the current implementation of `ReconstructESDCoincidences`, first reconstructing directions, then cores, so the direction reconstruction does not have access to core positions, so the `FlatRegression3D` is used. The dashed line simply reconstructs direction again after core reconstruction, this then uses the reconstructed core (in this case the simple `CenterMassAlgorithm`) with the `CurvedRegression3D`. The dotted line is for reconstructed directions using the input core position from the simulated core positions.

Todo:
- Check if altitude was correctly accounted for.
- Check if simulated station offsets are used.

angles_between

**Comment by 153957** [comment]
Implemented #141 in f5d3e45c54d01a8c083bd35ab07afa86a747499d.

Todo:
- [ ] Tests
- [ ] Check if corrections are correct
    - [ ] Is azimuth corrected correctly? (Check cluster rotation)
    - [ ] Correct - + ?
- [ ] Easy verification; reconstruct using 3D reconstruction.

**Comment by davidfokkema** [comment]
Niiiiiiice! 👍

**Comment by tomkooij** [comment]
Nice work!

Some small thoughts:

- Is there an easy way to exclude (real) core locations that are "outside" of the array? I guess they are reconstructed as "inside" the array by the `CenterMassAlgorithm', which does not help the direction reconstruction (if possible for the event at all).

- I wonder if we should exclude arrival times for particles with pulse-integrals below (say) 0.8 MIP (at large distances from the core). Low pulseintegral particles are probably photons. Because of the detection statistics there may be a large spread in arrival time (at large distance from the core). I think it is worth investigation if disregarding these improves the fit. (And/or implement a fancy likelihood fit). Perhaps just excluding low pulse-integrals (assume that implies large core distance) is enough.

**Comment by 153957** [comment]
- In the simulation I limited the core distance to ensure all core positions were close to the cluster center to have the highest probability of many stations with a detections.
- It was shown by David, and easily verified by simulations, that for reconstructions in a single station you should require at least 2 particles per detector to get reasonable direction accuracy (fig 4.14, 5.15). For larger showers this is slightly different because of the larger distance between the detectors. At large core distances the detection probability quickly decreases and if there is indeed a trigger the density if often low. This does not necessarily make it bad, but should be assumed to deviate more from the expected front. I also saw this in simulations where only leptons were used. The effect of gammas to the trigger and reconstructability needs to be investigated a bit more.

**Comment by 153957** [comment]
Seems to work well for inclined showers as well. I used a 22.5° shower. Again same linestyle indicators, so solid is the original FlatRegression3D. The dotted and curved are the CurvedRegression3D. Those are clearly better than the flat. (Note; I have not yet implemented the inclusion of a reconstructed energy to the shape of the shower front for the direction reconstruction).

screen shot 2016-05-29 at 21 20 30

**Comment by tomkooij** [comment]
Impressive!

**Comment by davidfokkema** [comment]
Impressive, indeed!

**Pull request merged**
