### PR TITLE
Implement Station.station_timing_offsets()

### PR DESCRIPTION
**Pull request by tomkooij**
```
>>> from sapphire.api import Station
>>> Station(501).station_timing_offset(1234567890, 504)
```
This uses (obviously not implemented yet):
http://data.hisparc.nl/show/source/station_timing_offsets/{station_1}/{station_2}/

Station numbers are always sorted: Only store ```/501/502``` and calculate ```/502/501```
The server needs to throw an error at ```/502/501```

Added reduced chi2 to ```sapphire.analysis.calibration.fit_timing_offset()```
- [x] check that **detector** timing offsets are unaffected (not unaffected but positive affection..)

### CODE REVIEW

**Comment by tomkooij** [comment]
I implemented using the offsets in ```ReconstructESDCoincidence```. I won't push it in this branch because it will break coincidence reconstructions if merged.

**Comment by 153957** [comment]
The urls now exist, they simply return 404, as they do now, but at least they exist.

**Comment by 153957** [comment]
The tests for detector timing offsets need to be updated. `fit_timing_offset` is patched/mocked, the mocked objects do not return two values, as the updated function actually does.

**Comment by tomkooij** [comment]
detector timing offsets are not 100% the same when fitting using sigma=sqrt(n+1):

The first is from the API. The second one is determined from ESD events (jan 1, 2015) using the "new" ```fit_timing_offset()``` (this branch)
```
In [17]: s.detector_timing_offset(ts)
Out[17]: [-1.0, 0.0, 6.25, 4.75]

In [18]: determine_detector_timing_offsets(events)
Out[18]: [-1.1886906393863272, 0.0, 6.1372088911564742, 4.7296738786524211]
```
The difference is not terribly large, but enough to investigate further (I'll compare a full year, when I have some time...)

**Comment by 153957** [comment]
Only the first value is significantly different.
Currently the offsets for the publicdb are rounded in 0.25 increments: https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/histograms/jobs.py#L690

This was done in the hope that if offsets do not change significantly they would remain equal over longer periods of time. Which would reduce the size of the Source TSV, because if the value remains equal the subsequent rows are skipped; https://github.com/HiSPARC/publicdb/blob/master/django_publicdb/status_display/views.py#L778
This might speed up reconstructions because the bisection to get the correct offsets would be faster. Unfortunately that does not seem to work that well. We might as well round to a single decimal, which will mean that all offsets will be included in the TSV files, except all nan values..

**Comment by tomkooij** [comment]
I compared some API offsets with calculated offsets from ```fit_timing_offset()``` (station 501, 2015):
compare_det_offsets
All offsets rounded to the nearest 0.25 ns.

Zoomed in on a small part of detector 1:
zoom

I think it is worth looking into the differences. Especially where the new fit fails, while the old worked. I'm curious how these offsets compare to ```numpy.mean()```

code: https://github.com/tomkooij/lio-project/commit/80ed010eb8b42631f9d015865cf069e1d59c62a8`

**Pull request merged**
