### PR TITLE
Cluster uptime

### PR DESCRIPTION
**Pull request by tomkooij**
I'd like to include cluster uptime in sapphire:

```
>>> from sapphire import ScienceParkCluster
>>> s = ScienceParkCluster()
>>> s.uptime(501)
51234   # hours
```

simultaneous uptime in (part of) a cluster:

```
>>> s = ScienceParkCluster()
>>> s.uptime([501, 502, 510])
12345   # hours
```
and use start and end datetime objects:

```
>>> from datetime import datetime
>>> s.uptime([501, 502, 510], start=datetime(2015,1,1), end=datettime(2015,12,31)
1234   # hours
```

The code (inspired, no stolen from topaz) is in my lio-project: https://github.com/tomkooij/lio-project/blob/master/driehoeken/cluster_uptime.py 

It is based on hourly eventhistograms:
- Downloading a single histogram from API is painfully slow (seconds)
- Storing all histograms in sapphire is 20 Megabytes (?) 
- Reading a histogram TSV from disk is slow (500 ms)
- I currently keep a cache of converted TSV in numpy bin format. This is FAST.

Do we want to store the histograms in the sapphire repository? 
(more later)

### CODE REVIEW

**Comment by tomkooij** [comment]
Sigh.
I did not mean to push the commits from the ```station_distances``` branch.
No time to fix this now.

**Comment by 153957** [comment]
Good idea. However, I think this would better fit in the `api.Network` and `api.Station` classes. Since those mostly deal with API/Source TSV calls. How large was the data when stored as numpy's `.npy` format? Does it help to store them compressed (`numpy.savez_compressed`)?

**Comment by tomkooij** [comment]
I'll figure out which classes are most suitable.

The tsvs are about 1Mbyte for "long running" stations. (Probably around 40Megs for the entire network).
.npy are about half size. npz does not save much. (10%?).

My current implementation uses a memoisation cache as a wrapper around the method that read the TSV/npy files, perhaps that is enough for most usage.

I'll probalby delete this and open a new branch and PR once I get around to implementing this.

**Comment by 153957** [comment]
And storing the data in HDF5 (with blosc:zlib and complevel 1), does that save space?

If we do add them to SAPPHiRE, like the other 'local' data files, it will quickly be out of date.
This is a slightly bigger problem than for things like GPS locations and station layouts..

**Comment by tomkooij** [comment]
Wild idea: Do the uptime calc on the publicdb side (daily) and implement and API that pushes uptime intervals (two timestamps foreach interval). That should be much faster.

In the meantime, let's implement this.

**Comment by 153957** [comment]
We could also add daily event time histograms (instead of hourly), that could reduce the data by a factor 24. Then only accept date objects for the interval, not datetime.. though we would still have the 'out of date' part..

**Pull request closed without merging**
