### PR TITLE
Implement force_fresh and force_stale for API

### PR DESCRIPTION
**Pull request by 153957**
These options replace the allow_stale option.
If both are false allow_stale is implied.
If either a true either local data will be used,
or data must be retrieved from the public database.
Move assignment of info to separate lazy method.
This speeds up initialisation of Station class.
It does not (yet) check if it is a valid station.

See #108 for some discussion

### CODE REVIEW

**Comment by tomkooij** [comment]
Nice!

**Comment by 153957** [comment]
Travis builds ~~are~~ were broken due to a conda issue.

**Comment by 153957** [comment]
I am still fixing the exceptions, warnings, and the tests.

**Comment by 153957** [comment]
Ok, that was a fairly large commit. Took some time to get it all right.

I added more local data so that the _get_json method works similar to the _get_tsv.
Both will first try getting fresh, but fall back to local data.
Not all data will be available locally, proper exceptions will be raised.

**Comment by tomkooij** [comment]
Nice! This looks like it is ready to be merged?

**Comment by 153957** [comment]
Yes, almost, I want to check a few more things before I do.

**Comment by 153957** [comment]
Hmm, that can be checked later..

**Pull request merged**
