### PR TITLE
Fix coincidences_tests when a station is added.

### PR DESCRIPTION
**Pull request by tomkooij**
When a station is added the /coincidences/s_index changes because of an extra
station. This causes tests to fail when a station is added.

Use Network(`force_stale=True`) to prevent such errors.

Fixes gh-164

### CODE REVIEW

**Comment by 153957** [comment]
Nice, elegantly solved 👍

**Comment by tomkooij** [comment]
@153957: I  `make update_local_data` (or something) is a good idea! I'll add it before merging.

**Comment by 153957** [comment]
Hmm, Perhaps the make command should be a bit different to indicate it will also update test data.
Since the name is currently the same as the installed command.
However, `make update_local_and_test_data` is a bit long..

**Comment by tomkooij** [comment]
I agree. `make update_data` ?

The makefile also referenced a commit from master (copy and paste mistake). I'll fix that...

**Comment by 153957** [comment]
Yes, `update_data` is ok.

**Pull request merged**
